<a href="https://colab.research.google.com/github/MiguelCortezPino/ProgramacionV-Marzo29/blob/master/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/MiguelCortezPino/datawarehouse-seguros.git

In [ ]:
import pandas as pd

Bloque 1 : Carga de Dataser

In [ ]:
#Ruta de dataset almacenada en la nube en githud
url = "https://raw.githubusercontent.com/MiguelCortezPino/datawarehouse-seguros/main/data/clientes.csv"

In [ ]:
#lectura del archivo
df = pd.read_csv(url)
print("dataset cargado correctamente")

dataset cargado correctamente

In [ ]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

Bloque 2: Exploraracion del Dataset

In [ ]:
print("primeras filas del dataser")
display(df.head())

primeras filas del dataser

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [ ]:
print("dimensiones del dataset (filas, columnas)")
display(df.shape)

dimensiones del dataset (filas, columnas)

(3030, 7)

In [ ]:
print("columnas del dataset")
display(df.columns)

columnas del dataset

Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [ ]:
print("tipos de datos")
print(df.dtypes)

tipos de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [ ]:
print("valores nulos por columnas")
print(df.isnull().sum())

valores nulos por columnas
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [ ]:
print("registro duplicados")
print(df.duplicated().sum())

registro duplicados
0

Bloque 3 : Limpieza de Datos

In [63]:
#elimina espacio al inicio y al final en columnas de texto
for con in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

#normalizar el nombre
df["nombre"]=df["nombre"].str.title()

#normalizar el email
df["email"]=df["email"].str.lower()

#normalizar genero
df["genero"]=df["genero"].str.lower()

#convertir fecha de nacimiento a formato fecha
df["fecha_nacimiento"]=pd.to_datetime(df["fecha_nacimiento"], format='mixed', dayfirst=True)

#Normalizar Ciudad
df["ciudad"]=df["ciudad"].str.title()
df["ciudad"]=df["ciudad"].str.strip()
df["ciudad"]=df["ciudad"].str.upper()
df["ciudad"]=df["ciudad"].str.replace(" ","")

#Limpieza de Segmento
df['segmento']=df['segmento'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

In [64]:
for col in df.columns:print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento

Bloque 4: Validacion de Datos

In [68]:
#crear columna para registro de errores
df["motivo_rechazo"] = ""

#validar id_cliente
df.loc[df["id_cliente"].isnull(),"motivo_rechazo"]="id_cliente nulo"